#! /bin/sh

LOCAL_LIB=$1
if [ ! -d "$LOCAL_LIB" ]; then
  LOCAL_LIB=
fi

CMAKE_OPT=
if [ x"$LOCAL_LIB" != x"" ]; then
  CMAKE_OPT="-D CMAKE_EXE_LINKER_FLAGS=-Wl,-L${LOCAL_LIB},-rpath,${LOCAL_LIB}"
fi

cmake .. \
  -D CMAKE_BUILD_TYPE=Release \
  -D BUILD_X=ON \
  -D USE_SDL=2 \
  -D BUILD_I286=ON \
  -D USE_ASYNCCPU=ON \
  $CMAKE_OPT
